spring:
     application:
               name: spring-boot-config
my:
 greeting: Hello World test
 appname: My App
 list:
    values: "one,two,three"
app:
   description: Welcome to $(my.appname)
db:
  connectionValues: "test-connection string"
  name : mydb
  port : 4000

management:
         endpoints:
                 web:
                   exposure:
                          include: "*"